name: Generate Snake Animation

on:
  # Run automatically every day, or customize schedule as needed
  schedule:
    - cron: "0 0 * * *"
  # Run manually by button
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3.3.0
        with:
          github_user_name: bekhzod-olimov
          outputs: |
            ./output/github-contribution-grid-snake.svg
      - name: Push the generated snake svg to the output branch
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate contribution snake"
          add: "./output/github-contribution-grid-snake.svg"
